ARG BASE_VERSION=latest
FROM ghcr.io/metadrop/aljibe-tools:${BASE_VERSION}
ARG UNLIGHTHOUSE_VERSION

USER root
RUN --mount=type=cache,target=/root/.npm npm install -g unlighthouse@$UNLIGHTHOUSE_VERSION

EXPOSE 5678
