ARG BASE_VERSION=latest
FROM ghcr.io/metadrop/aljibe-tools:${BASE_VERSION}
ARG PA11Y_VERSION

USER root
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends git; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

ARG PA11Y_CI_VERSION

RUN --mount=type=cache,target=/root/.npm \
    npm install -g pa11y@$PA11Y_VERSION pa11y-ci@$PA11Y_CI_VERSION git+https://gitlab.com/metadrop-public/pa11y-ci-reporter-html.git#feature/add-report-all-issues-option serve macieklewkowicz/pa11y-reporter-junit#pull/2/head
